micronaut:
  http:
    client:
      exception-on-error-status: false
  application:
    name: userRegister
  server:
    host: localhost
    port: 8080

datasources:
  default:
    url: ${JDBC_URL:`jdbc:h2:file:~/tmp/electricdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE`}
    username: ${JDBC_USER:sa}
    password: ${JDBC_PASSWORD:""}
    driverClassName: ${JDBC_DRIVER:org.h2.Driver}

jpa:
  default:
    entity-scan:
      packages:
        - com.app.electric.domain
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true

flyway:
  datasources:
    default:
      enabled: true
